main: feudalism.App
name: Feudalism
version: 0.1
api-version: 1.16
depend: [Vault]
commands:
  realm:
    description: Realm command
    usage: /<command>
    permission: feudalism.realm 
  admin:
    description: Admin command
    usage: /<command>
    permission: feudalism.admin 

permissions:
  feudalism.realm:
    description: Realm
    default: true
  feudalism.admin:
    description: Realm
    default: op